### ISSUE TITLE
keymap does not exist error on `npm run build`

### ISSUE THREAD

**Issue by Analect** [phosphorjs/phosphide-example#22]
I realise this may be a WIP ... but was just trying to get it up and running and hitting this problem when running `npm run build`.

```
tsc --project red && tsc --project green && tsc --project yellow && tsc --project blue && tsc --project editor && tsc --project application && webpack --config webpack.conf.js

application/index.ts(45,17): error TS2339: Property 'keymap' does not exist on type 'IShortcutManager'.
```
Thanks.

**Comment by sccolbert** [comment]
This should be fixed shortly. We're having a bit of churn with keymaps and commands at the moment.

**Comment by Analect** [comment]
Thanks for the update @sccolbert

**Comment by Leftium** [comment]
Is there any work-around for this? I'd just like to see what the example looks like.

**Comment by sccolbert** [comment]
@Leftium  This repo is no longer maintained. Everything has been merged into https://github.com/phosphorjs/phosphor

JupyterLab has been built on top of what the example was originally showing:
https://github.com/jupyterlab/jupyterlab
